version: "3.8"

services:
  mongo:
    image: mongo
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--oplogSize",
        "128"
      ]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      # rs.status() will throw an exception if the replica set is not initiated,
      # so we initiate it if it's not and perform the status check periodically
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      # data will be persisted in named volumes for use between container restarts
      # use `docker compose down -v` to remove the volumes
      - "mongo_data:/data/db"
      - "mongo_logs:/data/log/mongodb"
      - "mongo_config:/data/configdb"

volumes:
  mongo_data:
  mongo_logs:
  mongo_config:
